### ISSUE TITLE
Outline alternative solutions

### ISSUE THREAD

**Issue by szeestraten** [szeestraten/kidsakoder-minecraft#10]
A brief outline of alternative solutions. The relevance of this point depends on
your project. In general, you are expected to check if there are already
existing solutions available on the market or as open source and make an
evaluation of them. When you are evaluating different alternatives, it is
important to make clear your evaluation criteria. Evaluation should be
discussed with the customer and any choice should be agreed upon with the
customer.

**Comment by LHSkjong** [comment]
I am minor
