### ISSUE TITLE
Figure out how to schedule the creation/deletion of VM

### ISSUE THREAD

**Issue by szeestraten** [szeestraten/kidsakoder-minecraft#136]
We need to be able to schedule the creation and deletion of VMs somehow. We probably need a scheduler like [sched](https://docs.python.org/2/library/sched.html), [APScheduler](https://apscheduler.readthedocs.org/en/latest/) or [Celery](http://www.celeryproject.org/)

**Comment by Anddor** [comment]
http://docs.celeryproject.org/en/latest/reference/celery.app.task.html#celery.app.task.Task.apply_async
