### ISSUE TITLE
BUG: norwegian characters not showing correctly

### ISSUE THREAD

**Issue by Anddor** [szeestraten/kidsakoder-minecraft#62]
When inserting norwegian characters "ÆØÅ" into database, they do not show correctly in html. Problem in database or html?

**Comment by Anddor** [comment]
Update: Norwegian characters filled into the form will show correctly. Only happens with example data from schema.sql

**Comment by DeimosA** [comment]
Probably has to do with escaping characters. Is done automagically from forms

**Comment by Anddor** [comment]
Also problem when using prompt, but not when using the forms on the website. As prompt will not be used by users, mark as resolved for now.
