### ISSUE TITLE
Handle Redirect Creation Method

### ISSUE THREAD

**Issue by LHSkjong** [szeestraten/kidsakoder-minecraft#86]
Do #41 "Research JS Framework" BEFORE this task.

**Comment by szeestraten** [comment]
@LHSkjong What kind of redirect are we thinking of here?

**Comment by LHSkjong** [comment]
@szeestraten Switching out current creation buttons with their respective Creation Method Views within the Meeting Creation Page.

**Comment by DeimosA** [comment]
jQuery should be fine if ajax is really necessary for this
